version: 1.0.{build}
image:
- Visual Studio 2022
- Ubuntu
build: false
test_script:
- pwsh: |
    # Ensure CI/CD build has the right version of pester
    Install-Module Pester -Force -Scope CurrentUser -MinimumVersion 5.4.0 -MaximumVersion 5.4.999

    $testResultsFile = ".\TestsResults.xml"
    $res = Invoke-Pester -OutputFormat NUnitXml -OutputFile $testResultsFile -PassThru
    (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))
    if ($res.FailedCount -gt 0) {
        throw "$($res.FailedCount) tests failed."
    }
